/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import models.User;

/**
 *
 * @author vikas
 */
public class ViewPanel extends javax.swing.JPanel {
    
    private User newUser; 
    /**
     * Creates new form FormPanel
     */
    public ViewPanel() {
        initComponents();
    }
    
    public ViewPanel(User user){
        
        this.newUser = user; 
        initComponents();

        firstNameValue.setText(user.getFirstName());
        lastNameValue.setText(user.getLastName());
        emailValue.setText(user.getEmail());
        ageValue.setText(user.getAge());
        messageValue.setText(user.getMessage());
        genderValue.setText(user.getGender());
        patientLabelValue.setText(user.getType());        
        dateValue.setText(user.getDate());
        imageValue.setIcon(user.getIcon());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel1 = new javax.swing.JLabel();
        firstNameLable = new javax.swing.JLabel();
        firstNameLable1 = new javax.swing.JLabel();
        firstNameLable2 = new javax.swing.JLabel();
        firstNameLable3 = new javax.swing.JLabel();
        firstNameLable4 = new javax.swing.JLabel();
        firstNameLable5 = new javax.swing.JLabel();
        firstNameLable6 = new javax.swing.JLabel();
        firstNameLable7 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameValue = new javax.swing.JLabel();
        lastNameValue = new javax.swing.JLabel();
        ageValue = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        messageValue = new javax.swing.JLabel();
        patientLabelValue = new javax.swing.JLabel();
        genderValue = new javax.swing.JLabel();
        imageValue = new javax.swing.JLabel();
        firstNameLable8 = new javax.swing.JLabel();
        dateValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 206, 68));
        setPreferredSize(new java.awt.Dimension(700, 600));

        titleLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        titleLabel1.setText("View Panel");

        firstNameLable.setText("First Name: ");

        firstNameLable1.setText("Last Name:");

        firstNameLable2.setText("Age:");

        firstNameLable3.setText("Email:");

        firstNameLable4.setText("Message:");

        firstNameLable5.setText("Patinet Type:");

        firstNameLable6.setText("Gender:");

        firstNameLable7.setText("Image:");

        firstNameLable8.setText("Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLable1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLable)
                                .addGap(43, 43, 43)
                                .addComponent(firstNameLabel))
                            .addComponent(firstNameLable2)
                            .addComponent(firstNameLable3)
                            .addComponent(firstNameLable4)
                            .addComponent(firstNameLable5)
                            .addComponent(firstNameLable6))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameValue)
                            .addComponent(titleLabel1)
                            .addComponent(lastNameValue)
                            .addComponent(ageValue)
                            .addComponent(emailValue)
                            .addComponent(messageValue)
                            .addComponent(patientLabelValue)
                            .addComponent(genderValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLable8)
                        .addGap(67, 67, 67)
                        .addComponent(dateValue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLable7)
                        .addGap(75, 75, 75)
                        .addComponent(imageValue)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titleLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable1)
                    .addComponent(lastNameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable2)
                    .addComponent(ageValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable3)
                    .addComponent(emailValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable4)
                    .addComponent(messageValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable5)
                    .addComponent(patientLabelValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable6)
                    .addComponent(genderValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(dateValue)
                        .addGap(1, 1, 1))
                    .addComponent(firstNameLable8))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLable7)
                    .addComponent(imageValue))
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageValue;
    private javax.swing.JLabel dateValue;
    private javax.swing.JLabel emailValue;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLable;
    private javax.swing.JLabel firstNameLable1;
    private javax.swing.JLabel firstNameLable2;
    private javax.swing.JLabel firstNameLable3;
    private javax.swing.JLabel firstNameLable4;
    private javax.swing.JLabel firstNameLable5;
    private javax.swing.JLabel firstNameLable6;
    private javax.swing.JLabel firstNameLable7;
    private javax.swing.JLabel firstNameLable8;
    private javax.swing.JLabel firstNameValue;
    private javax.swing.JLabel genderValue;
    private javax.swing.JLabel imageValue;
    private javax.swing.JLabel lastNameValue;
    private javax.swing.JLabel messageValue;
    private javax.swing.JLabel patientLabelValue;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
